"""
Reference-free ensemble reranking for the proposed captioning model.

This module combines caption candidates generated by the ViT-T5 and
Swin-T5 branches using three signals:

    1. Beam-search sequence score
    2. CLIP image-text similarity
    3. Cross-candidate consensus similarity

No reference caption is required.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
import math
from typing import Any, Mapping, Sequence

import torch
from torch import Tensor, nn
import torch.nn.functional as F
from transformers import AutoProcessor, CLIPModel

from .beam_search import (
    BeamCandidate,
    BranchName,
    DualBeamSearchOutput,
)


@dataclass(frozen=True)
class EnsembleConfig:
    """
    Configuration for reference-free candidate reranking.

    The three score weights are normalized internally, so they do not
    have to sum to one.

    Attributes:
        beam_weight:
            Weight assigned to the normalized beam-search score.

        clip_weight:
            Weight assigned to normalized CLIP image-text similarity.

        consensus_weight:
            Weight assigned to normalized caption-consensus similarity.

        cross_branch_consensus:
            If True, each candidate is compared primarily with candidates
            generated by the other model branch. If no opposite-branch
            candidate exists, all other candidates are used as fallback.

        deduplicate_captions:
            If True, identical captions after lowercase/whitespace
            normalization are returned only once.

        reject_empty_captions:
            If True, empty decoded captions are removed before scoring.

        normalization_epsilon:
            Numerical tolerance used by min-max normalization.
    """

    beam_weight: float = 0.25
    clip_weight: float = 0.50
    consensus_weight: float = 0.25
    cross_branch_consensus: bool = True
    deduplicate_captions: bool = True
    reject_empty_captions: bool = True
    normalization_epsilon: float = 1e-8

    def validate(self) -> None:
        """Validate all reranking configuration values."""
        weight_values = {
            "beam_weight": self.beam_weight,
            "clip_weight": self.clip_weight,
            "consensus_weight": self.consensus_weight,
        }

        for name, value in weight_values.items():
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                raise TypeError(
                    f"{name} must be an int or float, "
                    f"but received {type(value).__name__}."
                )

            numeric_value = float(value)

            if not math.isfinite(numeric_value):
                raise ValueError(
                    f"{name} must be finite, but received {value}."
                )

            if numeric_value < 0.0:
                raise ValueError(
                    f"{name} must be greater than or equal to 0, "
                    f"but received {value}."
                )

        if (
            float(self.beam_weight)
            + float(self.clip_weight)
            + float(self.consensus_weight)
            <= 0.0
        ):
            raise ValueError(
                "At least one ensemble score weight must be greater than 0."
            )

        boolean_values = {
            "cross_branch_consensus": self.cross_branch_consensus,
            "deduplicate_captions": self.deduplicate_captions,
            "reject_empty_captions": self.reject_empty_captions,
        }

        for name, value in boolean_values.items():
            if not isinstance(value, bool):
                raise TypeError(
                    f"{name} must be a boolean, "
                    f"but received {type(value).__name__}."
                )

        if isinstance(self.normalization_epsilon, bool) or not isinstance(
            self.normalization_epsilon,
            (int, float),
        ):
            raise TypeError(
                "normalization_epsilon must be an int or float, "
                f"but received "
                f"{type(self.normalization_epsilon).__name__}."
            )

        epsilon = float(self.normalization_epsilon)

        if not math.isfinite(epsilon) or epsilon <= 0.0:
            raise ValueError(
                "normalization_epsilon must be finite and greater than 0, "
                f"but received {self.normalization_epsilon}."
            )

    @property
    def normalized_weights(self) -> tuple[float, float, float]:
        """Return beam, CLIP, and consensus weights summing to one."""
        total = (
            float(self.beam_weight)
            + float(self.clip_weight)
            + float(self.consensus_weight)
        )

        return (
            float(self.beam_weight) / total,
            float(self.clip_weight) / total,
            float(self.consensus_weight) / total,
        )


@dataclass(frozen=True)
class EnsembleCandidate:
    """Store all component scores for one reranked caption."""

    final_rank: int
    branch: BranchName
    source_rank: int
    text: str
    token_ids: tuple[int, ...]

    beam_score: float
    normalized_beam_score: float

    clip_score: float
    normalized_clip_score: float

    consensus_score: float
    normalized_consensus_score: float

    final_score: float


@dataclass(frozen=True)
class ImageEnsembleOutput:
    """Store ranked candidates and the selected caption for one image."""

    image_index: int
    best_candidate: EnsembleCandidate
    ranked_candidates: list[EnsembleCandidate]


@dataclass(frozen=True)
class EnsembleRerankOutput:
    """Store final reranking results for an image batch."""

    images: list[ImageEnsembleOutput]

    @property
    def best_captions(self) -> list[str]:
        """Return only the selected caption text for every image."""
        return [result.best_candidate.text for result in self.images]


class ReferenceFreeEnsembleReranker(nn.Module):
    """
    Rerank ViT-T5 and Swin-T5 beam candidates without references.

    CLIP cosine similarity is used for both image-text relevance and
    text-text consensus. All three component scores are min-max
    normalized independently inside each image's candidate pool before
    their weighted sum is calculated.
    """

    def __init__(
        self,
        clip_model: nn.Module,
        clip_processor: Any,
        config: EnsembleConfig | None = None,
        device: str | torch.device | None = None,
    ) -> None:
        """
        Initialize the reranker.

        Args:
            clip_model:
                A CLIP-compatible module exposing get_image_features()
                and get_text_features().

            clip_processor:
                A Hugging Face CLIP processor or compatible callable.

            config:
                Optional reranking configuration.

            device:
                Device used for CLIP scoring. If omitted, the current
                CLIP model parameter device is used when available.
        """
        super().__init__()

        if not isinstance(clip_model, nn.Module):
            raise TypeError(
                "clip_model must be an instance of nn.Module, "
                f"but received {type(clip_model).__name__}."
            )

        if not callable(getattr(clip_model, "get_image_features", None)):
            raise TypeError(
                "clip_model must expose a callable get_image_features method."
            )

        if not callable(getattr(clip_model, "get_text_features", None)):
            raise TypeError(
                "clip_model must expose a callable get_text_features method."
            )

        if not callable(clip_processor):
            raise TypeError(
                "clip_processor must be callable, "
                f"but received {type(clip_processor).__name__}."
            )

        if config is None:
            resolved_config = EnsembleConfig()
        elif isinstance(config, EnsembleConfig):
            resolved_config = config
        else:
            raise TypeError(
                "config must be an EnsembleConfig instance or None, "
                f"but received {type(config).__name__}."
            )

        resolved_config.validate()

        self.clip_model = clip_model
        self.clip_processor = clip_processor
        self.config = resolved_config
        self.device = self._resolve_device(
            model=clip_model,
            requested_device=device,
        )
        self.model_dtype = self._resolve_model_dtype(clip_model)

        self.clip_model.to(self.device)

    @classmethod
    def from_pretrained(
        cls,
        model_name: str = "openai/clip-vit-base-patch32",
        config: EnsembleConfig | None = None,
        device: str | torch.device | None = None,
        **from_pretrained_kwargs: Any,
    ) -> "ReferenceFreeEnsembleReranker":
        """
        Load a CLIP model and its matching processor.

        The model is downloaded only when this factory is called.
        """
        if not isinstance(model_name, str):
            raise TypeError(
                "model_name must be a string, "
                f"but received {type(model_name).__name__}."
            )

        if not model_name.strip():
            raise ValueError("model_name must not be empty.")

        clip_model = CLIPModel.from_pretrained(
            model_name,
            **from_pretrained_kwargs,
        )

        clip_processor = AutoProcessor.from_pretrained(
            model_name,
        )

        return cls(
            clip_model=clip_model,
            clip_processor=clip_processor,
            config=config,
            device=device,
        )

    @staticmethod
    def _resolve_device(
        model: nn.Module,
        requested_device: str | torch.device | None,
    ) -> torch.device:
        """Resolve the device used for CLIP inference."""
        if requested_device is not None:
            try:
                return torch.device(requested_device)
            except (TypeError, RuntimeError) as error:
                raise ValueError(
                    f"Invalid device value: {requested_device!r}."
                ) from error

        try:
            return next(model.parameters()).device
        except StopIteration:
            return torch.device("cpu")

    @staticmethod
    def _resolve_model_dtype(model: nn.Module) -> torch.dtype:
        """Return the dtype of the first floating-point parameter."""
        for parameter in model.parameters():
            if parameter.is_floating_point():
                return parameter.dtype

        return torch.float32

    @staticmethod
    def _move_mapping_to_device(
        values: Mapping[str, Any],
        device: torch.device,
    ) -> dict[str, Any]:
        """Move Tensor values from a processor batch to a device."""
        return {
            key: value.to(device) if torch.is_tensor(value) else value
            for key, value in values.items()
        }

    @staticmethod
    def _extract_feature_tensor(
        output: Any,
        output_name: str,
    ) -> Tensor:
        """Extract an embedding Tensor from a CLIP helper output."""
        if torch.is_tensor(output):
            return output

        for attribute_name in (
            "image_embeds",
            "text_embeds",
            "pooler_output",
        ):
            candidate = getattr(output, attribute_name, None)

            if torch.is_tensor(candidate):
                return candidate

        if isinstance(output, (tuple, list)) and output:
            if torch.is_tensor(output[0]):
                return output[0]

        raise TypeError(
            f"{output_name} must contain a Tensor embedding, "
            f"but received {type(output).__name__}."
        )

    @staticmethod
    def _normalize_caption_key(text: str) -> str:
        """Create a stable key for caption deduplication."""
        return " ".join(text.lower().split())

    def _min_max_normalize(
        self,
        scores: Sequence[float],
    ) -> list[float]:
        """
        Normalize finite scores to [0, 1].

        A constant score vector receives the neutral value 0.5 so the
        component neither rewards nor penalizes all candidates equally.
        """
        if not scores:
            raise ValueError("scores must contain at least one value.")

        numeric_scores = [float(score) for score in scores]

        for score in numeric_scores:
            if not math.isfinite(score):
                raise ValueError(
                    "All component scores must be finite, "
                    f"but received {score}."
                )

        minimum = min(numeric_scores)
        maximum = max(numeric_scores)
        score_range = maximum - minimum

        if score_range <= float(self.config.normalization_epsilon):
            return [0.5 for _ in numeric_scores]

        return [
            (score - minimum) / score_range
            for score in numeric_scores
        ]

    def _validate_and_collect_candidates(
        self,
        beam_output: DualBeamSearchOutput,
    ) -> list[list[BeamCandidate]]:
        """Validate beam output and merge both branches by image."""
        if not isinstance(beam_output, DualBeamSearchOutput):
            raise TypeError(
                "beam_output must be a DualBeamSearchOutput instance, "
                f"but received {type(beam_output).__name__}."
            )

        if beam_output.vit.branch != "vit":
            raise ValueError(
                "beam_output.vit.branch must equal 'vit'."
            )

        if beam_output.swin.branch != "swin":
            raise ValueError(
                "beam_output.swin.branch must equal 'swin'."
            )

        vit_groups = beam_output.vit.candidates
        swin_groups = beam_output.swin.candidates

        if len(vit_groups) != len(swin_groups):
            raise ValueError(
                "ViT and Swin candidate outputs must contain the same "
                "number of images. "
                f"ViT images: {len(vit_groups)}; "
                f"Swin images: {len(swin_groups)}."
            )

        if not vit_groups:
            raise ValueError(
                "beam_output must contain candidates for at least one image."
            )

        merged_groups: list[list[BeamCandidate]] = []

        for image_index, (vit_candidates, swin_candidates) in enumerate(
            zip(vit_groups, swin_groups, strict=True)
        ):
            merged_candidates = [
                *vit_candidates,
                *swin_candidates,
            ]

            validated_candidates: list[BeamCandidate] = []

            for candidate in merged_candidates:
                if not isinstance(candidate, BeamCandidate):
                    raise TypeError(
                        "Every candidate must be a BeamCandidate, "
                        f"but image {image_index} contains "
                        f"{type(candidate).__name__}."
                    )

                if candidate.branch not in {"vit", "swin"}:
                    raise ValueError(
                        f"Invalid candidate branch {candidate.branch!r} "
                        f"for image {image_index}."
                    )

                if not math.isfinite(float(candidate.beam_score)):
                    raise ValueError(
                        "Candidate beam scores must be finite. "
                        f"Image {image_index} contains "
                        f"{candidate.beam_score}."
                    )

                cleaned_text = candidate.text.strip()

                if not cleaned_text and self.config.reject_empty_captions:
                    continue

                if cleaned_text != candidate.text:
                    candidate = replace(
                        candidate,
                        text=cleaned_text,
                    )

                validated_candidates.append(candidate)

            if not validated_candidates:
                raise ValueError(
                    f"Image {image_index} has no usable caption candidates."
                )

            merged_groups.append(validated_candidates)

        return merged_groups

    def _prepare_clip_images(
        self,
        batch_size: int,
        clip_images: Sequence[Any] | Tensor | None,
        clip_pixel_values: Tensor | None,
    ) -> Tensor:
        """
        Build or validate CLIP pixel values.

        Exactly one of clip_images and clip_pixel_values must be given.
        """
        if (clip_images is None) == (clip_pixel_values is None):
            raise ValueError(
                "Provide exactly one of clip_images or clip_pixel_values."
            )

        if clip_pixel_values is not None:
            if not torch.is_tensor(clip_pixel_values):
                raise TypeError(
                    "clip_pixel_values must be a Tensor."
                )

            if clip_pixel_values.ndim != 4:
                raise ValueError(
                    "clip_pixel_values must have shape "
                    "(batch_size, channels, height, width)."
                )

            if clip_pixel_values.shape[0] != batch_size:
                raise ValueError(
                    "clip_pixel_values batch size must match beam output. "
                    f"Expected {batch_size}, but received "
                    f"{clip_pixel_values.shape[0]}."
                )

            return clip_pixel_values.to(
                device=self.device,
                dtype=self.model_dtype,
            )

        assert clip_images is not None

        if torch.is_tensor(clip_images):
            if clip_images.ndim != 4:
                raise ValueError(
                    "Tensor clip_images must have shape "
                    "(batch_size, channels, height, width)."
                )

            if clip_images.shape[0] != batch_size:
                raise ValueError(
                    "clip_images batch size must match beam output. "
                    f"Expected {batch_size}, but received "
                    f"{clip_images.shape[0]}."
                )

            processor_images: Sequence[Any] = [
                image.detach().cpu()
                for image in clip_images
            ]
        else:
            processor_images = list(clip_images)

            if len(processor_images) != batch_size:
                raise ValueError(
                    "clip_images length must match beam output. "
                    f"Expected {batch_size}, but received "
                    f"{len(processor_images)}."
                )

        processed_images = self.clip_processor(
            images=processor_images,
            return_tensors="pt",
        )

        if not isinstance(processed_images, Mapping):
            raise TypeError(
                "clip_processor image output must be a mapping."
            )

        pixel_values = processed_images.get("pixel_values")

        if not torch.is_tensor(pixel_values):
            raise RuntimeError(
                "clip_processor did not return Tensor pixel_values."
            )

        if pixel_values.shape[0] != batch_size:
            raise RuntimeError(
                "Processed CLIP image batch has an unexpected size. "
                f"Expected {batch_size}, but received "
                f"{pixel_values.shape[0]}."
            )

        return pixel_values.to(
            device=self.device,
            dtype=self.model_dtype,
        )

    def _encode_clip_features(
        self,
        texts: list[str],
        batch_size: int,
        clip_images: Sequence[Any] | Tensor | None,
        clip_pixel_values: Tensor | None,
    ) -> tuple[Tensor, Tensor]:
        """Encode normalized CLIP image and text embeddings."""
        if not texts:
            raise ValueError("texts must contain at least one caption.")

        pixel_values = self._prepare_clip_images(
            batch_size=batch_size,
            clip_images=clip_images,
            clip_pixel_values=clip_pixel_values,
        )

        processed_text = self.clip_processor(
            text=texts,
            padding=True,
            truncation=True,
            return_tensors="pt",
        )

        if not isinstance(processed_text, Mapping):
            raise TypeError(
                "clip_processor text output must be a mapping."
            )

        text_inputs = self._move_mapping_to_device(
            values=processed_text,
            device=self.device,
        )

        allowed_text_keys = {
            "input_ids",
            "attention_mask",
            "position_ids",
        }

        text_inputs = {
            key: value
            for key, value in text_inputs.items()
            if key in allowed_text_keys
        }

        if "input_ids" not in text_inputs:
            raise RuntimeError(
                "clip_processor did not return text input_ids."
            )

        was_training = self.clip_model.training
        self.clip_model.eval()

        try:
            with torch.inference_mode():
                image_output = self.clip_model.get_image_features(
                    pixel_values=pixel_values,
                )

                text_output = self.clip_model.get_text_features(
                    **text_inputs,
                )
        finally:
            self.clip_model.train(was_training)

        image_features = self._extract_feature_tensor(
            image_output,
            output_name="CLIP image feature output",
        )

        text_features = self._extract_feature_tensor(
            text_output,
            output_name="CLIP text feature output",
        )

        if image_features.ndim != 2:
            raise RuntimeError(
                "CLIP image features must be a 2D Tensor, "
                f"but received shape {tuple(image_features.shape)}."
            )

        if text_features.ndim != 2:
            raise RuntimeError(
                "CLIP text features must be a 2D Tensor, "
                f"but received shape {tuple(text_features.shape)}."
            )

        if image_features.shape[0] != batch_size:
            raise RuntimeError(
                "Unexpected number of CLIP image embeddings. "
                f"Expected {batch_size}, but received "
                f"{image_features.shape[0]}."
            )

        if text_features.shape[0] != len(texts):
            raise RuntimeError(
                "Unexpected number of CLIP text embeddings. "
                f"Expected {len(texts)}, but received "
                f"{text_features.shape[0]}."
            )

        if image_features.shape[-1] != text_features.shape[-1]:
            raise RuntimeError(
                "CLIP image and text embedding dimensions must match. "
                f"Image dimension: {image_features.shape[-1]}; "
                f"text dimension: {text_features.shape[-1]}."
            )

        image_features = F.normalize(
            image_features.float(),
            p=2,
            dim=-1,
        )

        text_features = F.normalize(
            text_features.float(),
            p=2,
            dim=-1,
        )

        return image_features, text_features

    def _compute_consensus_scores(
        self,
        candidates: list[BeamCandidate],
        text_features: Tensor,
    ) -> list[float]:
        """Compute mean cosine agreement for each caption candidate."""
        candidate_count = len(candidates)

        if text_features.shape[0] != candidate_count:
            raise ValueError(
                "Candidate and text-feature counts must match."
            )

        if candidate_count == 1:
            return [0.0]

        similarity_matrix = text_features @ text_features.transpose(0, 1)
        consensus_scores: list[float] = []

        for candidate_index, candidate in enumerate(candidates):
            peer_indices: list[int] = []

            if self.config.cross_branch_consensus:
                peer_indices = [
                    peer_index
                    for peer_index, peer_candidate in enumerate(candidates)
                    if (
                        peer_index != candidate_index
                        and peer_candidate.branch != candidate.branch
                    )
                ]

            if not peer_indices:
                peer_indices = [
                    peer_index
                    for peer_index in range(candidate_count)
                    if peer_index != candidate_index
                ]

            if not peer_indices:
                consensus_scores.append(0.0)
                continue

            peer_similarities = similarity_matrix[
                candidate_index,
                peer_indices,
            ]

            consensus_scores.append(
                float(peer_similarities.mean().item())
            )

        return consensus_scores

    def _rank_image_candidates(
        self,
        candidates: list[BeamCandidate],
        clip_scores: list[float],
        consensus_scores: list[float],
    ) -> list[EnsembleCandidate]:
        """Normalize component scores and rank one image's candidates."""
        candidate_count = len(candidates)

        if len(clip_scores) != candidate_count:
            raise ValueError(
                "clip_scores length must match candidate count."
            )

        if len(consensus_scores) != candidate_count:
            raise ValueError(
                "consensus_scores length must match candidate count."
            )

        beam_scores = [
            float(candidate.beam_score)
            for candidate in candidates
        ]

        normalized_beam = self._min_max_normalize(beam_scores)
        normalized_clip = self._min_max_normalize(clip_scores)
        normalized_consensus = self._min_max_normalize(
            consensus_scores
        )

        beam_weight, clip_weight, consensus_weight = (
            self.config.normalized_weights
        )

        scored_candidates: list[EnsembleCandidate] = []

        for index, candidate in enumerate(candidates):
            final_score = (
                beam_weight * normalized_beam[index]
                + clip_weight * normalized_clip[index]
                + consensus_weight * normalized_consensus[index]
            )

            scored_candidates.append(
                EnsembleCandidate(
                    final_rank=0,
                    branch=candidate.branch,
                    source_rank=candidate.rank,
                    text=candidate.text,
                    token_ids=candidate.token_ids,
                    beam_score=beam_scores[index],
                    normalized_beam_score=normalized_beam[index],
                    clip_score=float(clip_scores[index]),
                    normalized_clip_score=normalized_clip[index],
                    consensus_score=float(consensus_scores[index]),
                    normalized_consensus_score=(
                        normalized_consensus[index]
                    ),
                    final_score=float(final_score),
                )
            )

        scored_candidates.sort(
            key=lambda item: (
                item.final_score,
                item.normalized_clip_score,
                item.normalized_consensus_score,
                item.normalized_beam_score,
            ),
            reverse=True,
        )

        if self.config.deduplicate_captions:
            deduplicated: list[EnsembleCandidate] = []
            seen_caption_keys: set[str] = set()

            for candidate in scored_candidates:
                caption_key = self._normalize_caption_key(
                    candidate.text
                )

                if caption_key in seen_caption_keys:
                    continue

                seen_caption_keys.add(caption_key)
                deduplicated.append(candidate)

            scored_candidates = deduplicated

        return [
            replace(candidate, final_rank=rank)
            for rank, candidate in enumerate(
                scored_candidates,
                start=1,
            )
        ]

    def rerank(
        self,
        beam_output: DualBeamSearchOutput,
        *,
        clip_images: Sequence[Any] | Tensor | None = None,
        clip_pixel_values: Tensor | None = None,
    ) -> EnsembleRerankOutput:
        """
        Rerank caption candidates for every image.

        Args:
            beam_output:
                Candidate groups produced by DualBranchBeamSearchGenerator.

            clip_images:
                Raw images accepted by the CLIP processor. Tensor input
                should contain raw image values rather than tensors already
                normalized for ViT or Swin.

            clip_pixel_values:
                Image batch already preprocessed for CLIP, with shape
                (batch_size, 3, clip_height, clip_width).

        Returns:
            Ranked candidates and one selected caption for every image.

        Exactly one of clip_images and clip_pixel_values must be supplied.
        """
        candidate_groups = self._validate_and_collect_candidates(
            beam_output
        )

        flat_candidates: list[BeamCandidate] = []
        flat_image_indices: list[int] = []
        group_ranges: list[tuple[int, int]] = []

        for image_index, candidates in enumerate(candidate_groups):
            start = len(flat_candidates)
            flat_candidates.extend(candidates)
            flat_image_indices.extend(
                [image_index] * len(candidates)
            )
            end = len(flat_candidates)
            group_ranges.append((start, end))

        texts = [candidate.text for candidate in flat_candidates]

        image_features, text_features = self._encode_clip_features(
            texts=texts,
            batch_size=len(candidate_groups),
            clip_images=clip_images,
            clip_pixel_values=clip_pixel_values,
        )

        image_index_tensor = torch.tensor(
            flat_image_indices,
            dtype=torch.long,
            device=image_features.device,
        )

        matching_image_features = image_features.index_select(
            0,
            image_index_tensor,
        )

        flat_clip_scores_tensor = (
            matching_image_features * text_features
        ).sum(dim=-1)

        image_results: list[ImageEnsembleOutput] = []

        for image_index, (start, end) in enumerate(group_ranges):
            image_candidates = flat_candidates[start:end]
            image_text_features = text_features[start:end]

            image_clip_scores = [
                float(score)
                for score in (
                    flat_clip_scores_tensor[start:end]
                    .detach()
                    .cpu()
                    .tolist()
                )
            ]

            image_consensus_scores = (
                self._compute_consensus_scores(
                    candidates=image_candidates,
                    text_features=image_text_features,
                )
            )

            ranked_candidates = self._rank_image_candidates(
                candidates=image_candidates,
                clip_scores=image_clip_scores,
                consensus_scores=image_consensus_scores,
            )

            if not ranked_candidates:
                raise RuntimeError(
                    f"Reranking produced no candidates for image "
                    f"{image_index}."
                )

            image_results.append(
                ImageEnsembleOutput(
                    image_index=image_index,
                    best_candidate=ranked_candidates[0],
                    ranked_candidates=ranked_candidates,
                )
            )

        return EnsembleRerankOutput(
            images=image_results,
        )